[Enhance] Add support for renaming columns via the `change` clause.
tithely/exo pull request #22
Opened 2021-10-07 04:24 UTC by ryanrigby17

This PR adds support for the `change` clause to allow renaming columns.
Portions I'm still not 100% on are the code parts concerning reversing/applying migrations on-top of other migrations. They will likely need closer scrutiny. 

I hope to follow this up with another PR for renaming tables, if this PR proves valuable.

2021-10-08 00:36 UTC, joshmcrae requested changes
This looks good! I've left some recommendations below with regards to code simplicity and developer experience, however as you noted in the PR description more time does need to be spent making sure reversal / application of the new operation works.

I'm happy to help out here, but I'll explain how this is intended to work first.

**Reversal**

Reversal is simply concerned with transforming an operation so that it can be used in a rollback. For the `CHANGE COLUMN old_col_name new_col_name column_definition` operation, reversal involves switching the order of names and replacing `column_definition` with whatever it was prior to the change. If `MODIFY COLUMN` has been implemented correctly already, this should be trivial as you'll just have to deal with swapping the names.

**Application**

This is concerned with 'reducing' multiple operations for the same thing (e.g. a table or column) such that a single SQL query needs to be executed rather than several individual queries. This is most useful when creating a new tenant database as each table can be created according to the entire history of migrations through one `CREATE TABLE` command, instead of a `CREATE TABLE` followed by several `ALTER TABLE` commands.

What's unique about this new operation is that after it is executed, the column has a different name. Since we look for previous operations by column name, we _might_ end up missing previous operations or reducing operations that aren't relevant. I say might because I haven't had time to think through this thoroughly. Given that we only apply one operation to another at a time, this might not be a problem.

At the very least, you'll need some logic added around `TableOperation.php:219` as well as what you've already got, because this handles the application of an `ALTER TABLE` to a `CREATE TABLE`.

Here are some scenarios to think about:

1. Applying a `CHANGE COLUMN` to an `ADD COLUMN` should result in an `ADD COLUMN` for the new name and column definition.
2. Applying a `CHANGE COLUMN` to a `MODIFY COLUMN` should result in a `MODIFY COLUMN` for the new name and column definition.
3. Applying a `CHANGE COLUMN` to a `CHANGE COLUMN` should result in a `CHANGE COLUMN` for the new name and definition. In the case that the names are the same (but switched) between them and the column definitions are identical, the operation shouldn't happen at all because there's no net change.

Writing all of this down, it seems to me like this should work identically to `MODIFY COLUMN` except that the column operation's name (column name) should be the new column name.

See if you can work this logic into your changes and I'll help out if needed.

2021-10-08 00:36 UTC, joshmcrae commented on src/Operation/TableOperation.php
> +            if ($columnOperation->getOperation() === ColumnOperation::CHANGE) {
This condition could be combined with the previous (as you've done with the switch statement lower down).

The second argument to `ColumnOperation` just needs to be changed to `$columnOperation->getOperation()`.

2021-10-08 00:36 UTC, joshmcrae commented on src/Statement/MysqlStatementBuilder.php
> +                                'CHANGE COLUMN %s',
Instead of the new conditional in `buildColumn()`, it's probably cleaner to change this to `CHANGE COLUMN %s %s` and use `$columnOperation->getOptions()['name']` for the first placeholder, leaving the existing `$this->buildColumn()` call in place as the second placeholder.

2021-10-08 00:36 UTC, joshmcrae commented on src/TableMigration.php
> +    public function changeColumn(string $column, array $options): TableMigration
This method would be more developer friendly if it had an additional argument for the new column name. An argument forces it to be provided and removes the need for checking that the `$options['name']` key has been set (which I don't think is happening anywhere).

It can still be pushed into `$options` key internally when constructing the `ColumnOperation` instance.

2021-10-12 23:50 UTC, saria3rabbi approved these changes, later dismissed
Looks like it's gonna work!
P.S. @ryanrigby17 do you think we should add more test cases to test Josh's example scenarios?

2021-10-13 00:02 UTC, ryanrigby17 commented
@saria3rabbi Definitely, I think more tests would be great. I'm still trying to fully wrap my head around the intricacies of them 😅

2021-10-13 01:04 UTC, ryanrigby17 commented
@joshmcrae Thanks for the excellent write up. I've made changes based on what you've written and your review recommendations. This feels more correct now. I feel like the best way to test these now will be via running the actual migration commands. How are the migrations within the tests folder actually used? I was wonder if I should add some change command and see if they are working correctly.

2021-10-13 22:36 UTC, joshmcrae commented
@ryanrigby17  those migrates are only used by `FinderTest` currently, to make sure it can read from the filesystem and construct a properly ordered history. It wouldn't be a bad idea to write some integration tests that use migrations in that directory and evaluate that the reduced operations come out as expected.

A class like `MigrationIntegrationTest` should do the trick. If you want to create a `tests/fixtures` directory to put different sets of migrations under (e.g. a directory per test case), go ahead! This kind of coverage would provide confidence that the complex scenarios are handled correctly.

2021-10-15 04:59 UTC, ryanrigby17 commented
@joshmcrae I've created a test case that utilizes migrations based on your provided examples. I'm happy that it's working how I still have one question regarding reducing ColumnOperations. The test case `testReduceRewindMigrationsWithChange` in the new `MigrationIntegrationTest` file still produces 2 ColumnOperations when it reduces the two TableOperations. Is this to be expected? I imagine it would be best to have it `DROP` the column and ignore the `CHANGE`, but I can't find an elegant solution for that.

2021-10-17 22:56 UTC, joshmcrae commented
@ryanrigby17 It will have to be a single column operation, as you can't rename a column and then drop it by its new name in a single SQL statement. In other words, the following would not work:

```sql
ALTER TABLE users
CHANGE user_id username varchar(255),
DROP COLUMN username;
```

You'll get `Can't DROP 'username'; check that column/key exists`.

The reason it's not reducing those operations is because the name field for the `CHANGE` does not match that of the `DROP` and thus they're not seen as operations relating to the same column. This has prompted me to realise that reducing the following two migrations likely won't work either:

1. Rename `username` column to `email`
2. Add `username` column

In this case they **do** share the same name and will be applied, but you cannot apply an `INSERT` to an `ALTER` or `CHANGE`.

We'll need to introduce the concept of 'before' and 'after' names for column operations. That way we can apply column operations for a given 'before' name to operations with a matching 'after' name.

2025-10-30 02:55 UTC, joshmcrae approved these changes

2025-10-30 02:56 UTC, merged